### PR TITLE
chore: vision camera 4 compatibility

### PR DESCRIPTION
**Pull request by 404-html**
https://github.com/gev2002/react-native-vision-camera-v3-text-recognition/issues/14
Android 🆗
iOS 🆗

It's up to library author if he want's create new repo or push that to existing one.

### CODE REVIEW

**Comment by gev2002** [comment]
Hey, Thank you for supporting, but this is plugin for Vision Camera V3 Not form V4.

**Comment by gev2002** [comment]
I'll create new repo and update logic for plugin for more performance.I'll happy to see you in new repo.

**Comment by 404-html** [comment]
> I'll create new repo and update logic for plugin for more performance.I'll happy to see you in new repo.

Thanks, I am happy to contribute.

**Comment by beatlecz** [comment]
> I'll create new repo and update logic for plugin for more performance.I'll happy to see you in new repo.

We are really looking forward for new repo. We have an app in development, and expo sdk 50 supports only vision camera v4 ... We are able to pay you to speed up the creating and releasing v4 plugin.

**Comment by 404-html** [comment]
> > I'll create new repo and update logic for plugin for more performance.I'll happy to see you in new repo.
> 
> We are really looking forward for new repo. We have an app in development, and expo sdk 50 supports only vision camera v4 ... We are able to pay you to speed up the creating and releasing v4 plugin.

@beatlecz as a temporary workaround you can use use my branch, which works with vision camera v4. In `package.json`:
```
"react-native-vision-camera-v3-text-recognition": "github:404-html/react-native-vision-camera-v3-text-recognition#chore/vision-camera-4-compatibility",
```

**Comment by gev2002** [comment]
> > I'll create new repo and update logic for plugin for more performance.I'll happy to see you in new repo.
> 
> 
> 
> We are really looking forward for new repo. We have an app in development, and expo sdk 50 supports only vision camera v4 ... We are able to pay you to speed up the creating and releasing v4 plugin. 

Hi there, If you want to I speed up and releasing V4 plugin You can sponsor me.For communication, and sponsoring you can write me to gmail gev.avet.02@gmail.com

**Comment by beatlecz** [comment]
> > > I'll create new repo and update logic for plugin for more performance.I'll happy to see you in new repo.
> > 
> > 
> > We are really looking forward for new repo. We have an app in development, and expo sdk 50 supports only vision camera v4 ... We are able to pay you to speed up the creating and releasing v4 plugin.
> 
> @beatlecz as a temporary workaround you can use use my branch, which works with vision camera v4. In `package.json`:
> 
> ```
> "react-native-vision-camera-v3-text-recognition": "github:404-html/react-native-vision-camera-v3-text-recognition#chore/vision-camera-4-compatibility",
> ```

Thx. But I have tried to install the package from github branch with this error result:
```
npm ERR! code 1
npm ERR! git dep preparation failed
npm ERR! command /Users/mirek/.nvm/versions/node/v18.17.1/bin/node /Users/mirek/.nvm/versions/node/v18.17.1/lib/node_modules/npm/bin/npm-cli.js install --force --cache=/Users/mirek/.npm --prefer-offline=false --prefer-online=false --offline=false --no-progress --no-save --no-audit --include=dev --include=peer --include=optional --no-package-lock-only --no-dry-run
npm ERR! > react-native-vision-camera-v3-text-recognition@1.1.1 prepare
npm ERR! > bob build
npm ERR! 
npm ERR! ℹ Building target commonjs
npm ERR! ℹ Cleaning up previous build at lib/commonjs
npm ERR! ℹ Compiling 3 files in src with babel
npm ERR! ✔ Wrote files to lib/commonjs
npm ERR! ℹ Building target module
npm ERR! ℹ Cleaning up previous build at lib/module
npm ERR! ℹ Compiling 3 files in src with babel
npm ERR! ✔ Wrote files to lib/module
npm ERR! ℹ Building target typescript
npm ERR! ℹ Cleaning up previous build at lib/typescript
npm ERR! ℹ Generating type definitions with tsc
npm ERR! src/index.tsx:7:10 - error TS2724: '"react-native-worklets-core"' has no exported member named 'useRunInJS'. Did you mean 'useRunOnJS'?
npm ERR! 
npm ERR! 7 import { useRunInJS } from 'react-native-worklets-core';
npm ERR!            ~~~~~~~~~~
npm ERR! 
npm ERR!   node_modules/react-native-worklets-core/lib/typescript/hooks/useRunOnJS.d.ts:20:25
npm ERR!     20 export declare function useRunOnJS<T extends (...args: any[]) => any>(callback: T, dependencyList: DependencyList): (...args: Parameters<T>) => Promise<ReturnType<T>>;
npm ERR!                                ~~~~~~~~~~
npm ERR!     'useRunOnJS' is declared here.
npm ERR! 
npm ERR! src/types.ts:3:3 - error TS2724: '"react-native-vision-camera"' has no exported member named 'FrameProcessor'. Did you mean 'useFrameProcessor'?
npm ERR! 
npm ERR! 3   FrameProcessor,
npm ERR!     ~~~~~~~~~~~~~~
npm ERR! 
npm ERR!   node_modules/react-native-vision-camera/lib/typescript/hooks/useFrameProcessor.d.ts:33:25
npm ERR!     33 export declare function useFrameProcessor(frameProcessor: (frame: Frame) => void, dependencies: DependencyList): ReadonlyFrameProcessor;
npm ERR!                                ~~~~~~~~~~~~~~~~~
npm ERR!     'useFrameProcessor' is declared here.
npm ERR! 
npm ERR! 
npm ERR! Found 2 errors in 2 files.
npm ERR! 
npm ERR! Errors  Files
npm ERR!      1  src/index.tsx:7
npm ERR!      1  src/types.ts:3
npm ERR! ✖ Failed to build definition files.
npm ERR! npm WARN using --force Recommended protections disabled.
```

**Comment by gev2002** [comment]
> > > > I'll create new repo and update logic for plugin for more performance.I'll happy to see you in new repo.
> > > 
> > > 
> > > We are really looking forward for new repo. We have an app in development, and expo sdk 50 supports only vision camera v4 ... We are able to pay you to speed up the creating and releasing v4 plugin.
> > 
> > 
> > @beatlecz as a temporary workaround you can use use my branch, which works with vision camera v4. In `package.json`:
> > ```
> > "react-native-vision-camera-v3-text-recognition": "github:404-html/react-native-vision-camera-v3-text-recognition#chore/vision-camera-4-compatibility",
> > ```
> 
> Thx. But I have tried to install the package from github branch with this error result:
> 
> ```
> npm ERR! code 1
> npm ERR! git dep preparation failed
> npm ERR! command /Users/mirek/.nvm/versions/node/v18.17.1/bin/node /Users/mirek/.nvm/versions/node/v18.17.1/lib/node_modules/npm/bin/npm-cli.js install --force --cache=/Users/mirek/.npm --prefer-offline=false --prefer-online=false --offline=false --no-progress --no-save --no-audit --include=dev --include=peer --include=optional --no-package-lock-only --no-dry-run
> npm ERR! > react-native-vision-camera-v3-text-recognition@1.1.1 prepare
> npm ERR! > bob build
> npm ERR! 
> npm ERR! ℹ Building target commonjs
> npm ERR! ℹ Cleaning up previous build at lib/commonjs
> npm ERR! ℹ Compiling 3 files in src with babel
> npm ERR! ✔ Wrote files to lib/commonjs
> npm ERR! ℹ Building target module
> npm ERR! ℹ Cleaning up previous build at lib/module
> npm ERR! ℹ Compiling 3 files in src with babel
> npm ERR! ✔ Wrote files to lib/module
> npm ERR! ℹ Building target typescript
> npm ERR! ℹ Cleaning up previous build at lib/typescript
> npm ERR! ℹ Generating type definitions with tsc
> npm ERR! src/index.tsx:7:10 - error TS2724: '"react-native-worklets-core"' has no exported member named 'useRunInJS'. Did you mean 'useRunOnJS'?
> npm ERR! 
> npm ERR! 7 import { useRunInJS } from 'react-native-worklets-core';
> npm ERR!            ~~~~~~~~~~
> npm ERR! 
> npm ERR!   node_modules/react-native-worklets-core/lib/typescript/hooks/useRunOnJS.d.ts:20:25
> npm ERR!     20 export declare function useRunOnJS<T extends (...args: any[]) => any>(callback: T, dependencyList: DependencyList): (...args: Parameters<T>) => Promise<ReturnType<T>>;
> npm ERR!                                ~~~~~~~~~~
> npm ERR!     'useRunOnJS' is declared here.
> npm ERR! 
> npm ERR! src/types.ts:3:3 - error TS2724: '"react-native-vision-camera"' has no exported member named 'FrameProcessor'. Did you mean 'useFrameProcessor'?
> npm ERR! 
> npm ERR! 3   FrameProcessor,
> npm ERR!     ~~~~~~~~~~~~~~
> npm ERR! 
> npm ERR!   node_modules/react-native-vision-camera/lib/typescript/hooks/useFrameProcessor.d.ts:33:25
> npm ERR!     33 export declare function useFrameProcessor(frameProcessor: (frame: Frame) => void, dependencies: DependencyList): ReadonlyFrameProcessor;
> npm ERR!                                ~~~~~~~~~~~~~~~~~
> npm ERR!     'useFrameProcessor' is declared here.
> npm ERR! 
> npm ERR! 
> npm ERR! Found 2 errors in 2 files.
> npm ERR! 
> npm ERR! Errors  Files
> npm ERR!      1  src/index.tsx:7
> npm ERR!      1  src/types.ts:3
> npm ERR! ✖ Failed to build definition files.
> npm ERR! npm WARN using --force Recommended protections disabled.
> ```

This error means that useRunInJs does not exist in work modules, now it is useRunOnJs, you can pay me and I will speed up the creation of a new package and help fix further errors.

**Comment by 404-html** [comment]
@beatlecz make sure you are using `react-native-worklets-core` v `1.3.3`, as stated [here](https://github.com/gev2002/react-native-vision-camera-v3-text-recognition/pull/17/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R4).

**Comment by beatlecz** [comment]
> @beatlecz make sure you are using `react-native-worklets-core` v `1.3.3`, as stated [here](https://github.com/gev2002/react-native-vision-camera-v3-text-recognition/pull/17/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R4).

Yes I have 1.3.3 of worklets. I have tried to delete node_modules and install again 🤔 without success.

**Comment by beatlecz** [comment]
> > > > > I'll create new repo and update logic for plugin for more performance.I'll happy to see you in new repo.
> 
> > > > 
> 
> > > > 
> 
> > > > We are really looking forward for new repo. We have an app in development, and expo sdk 50 supports only vision camera v4 ... We are able to pay you to speed up the creating and releasing v4 plugin.
> 
> > > 
> 
> > > 
> 
> > > @beatlecz as a temporary workaround you can use use my branch, which works with vision camera v4. In `package.json`:
> 
> > > ```
> 
> > > "react-native-vision-camera-v3-text-recognition": "github:404-html/react-native-vision-camera-v3-text-recognition#chore/vision-camera-4-compatibility",
> 
> > > ```
> 
> > 
> 
> > Thx. But I have tried to install the package from github branch with this error result:
> 
> > 
> 
> > ```
> 
> > npm ERR! code 1
> 
> > npm ERR! git dep preparation failed
> 
> > npm ERR! command /Users/mirek/.nvm/versions/node/v18.17.1/bin/node /Users/mirek/.nvm/versions/node/v18.17.1/lib/node_modules/npm/bin/npm-cli.js install --force --cache=/Users/mirek/.npm --prefer-offline=false --prefer-online=false --offline=false --no-progress --no-save --no-audit --include=dev --include=peer --include=optional --no-package-lock-only --no-dry-run
> 
> > npm ERR! > react-native-vision-camera-v3-text-recognition@1.1.1 prepare
> 
> > npm ERR! > bob build
> 
> > npm ERR! 
> 
> > npm ERR! ℹ Building target commonjs
> 
> > npm ERR! ℹ Cleaning up previous build at lib/commonjs
> 
> > npm ERR! ℹ Compiling 3 files in src with babel
> 
> > npm ERR! ✔ Wrote files to lib/commonjs
> 
> > npm ERR! ℹ Building target module
> 
> > npm ERR! ℹ Cleaning up previous build at lib/module
> 
> > npm ERR! ℹ Compiling 3 files in src with babel
> 
> > npm ERR! ✔ Wrote files to lib/module
> 
> > npm ERR! ℹ Building target typescript
> 
> > npm ERR! ℹ Cleaning up previous build at lib/typescript
> 
> > npm ERR! ℹ Generating type definitions with tsc
> 
> > npm ERR! src/index.tsx:7:10 - error TS2724: '"react-native-worklets-core"' has no exported member named 'useRunInJS'. Did you mean 'useRunOnJS'?
> 
> > npm ERR! 
> 
> > npm ERR! 7 import { useRunInJS } from 'react-native-worklets-core';
> 
> > npm ERR!            ~~~~~~~~~~
> 
> > npm ERR! 
> 
> > npm ERR!   node_modules/react-native-worklets-core/lib/typescript/hooks/useRunOnJS.d.ts:20:25
> 
> > npm ERR!     20 export declare function useRunOnJS<T extends (...args: any[]) => any>(callback: T, dependencyList: DependencyList): (...args: Parameters<T>) => Promise<ReturnType<T>>;
> 
> > npm ERR!                                ~~~~~~~~~~
> 
> > npm ERR!     'useRunOnJS' is declared here.
> 
> > npm ERR! 
> 
> > npm ERR! src/types.ts:3:3 - error TS2724: '"react-native-vision-camera"' has no exported member named 'FrameProcessor'. Did you mean 'useFrameProcessor'?
> 
> > npm ERR! 
> 
> > npm ERR! 3   FrameProcessor,
> 
> > npm ERR!     ~~~~~~~~~~~~~~
> 
> > npm ERR! 
> 
> > npm ERR!   node_modules/react-native-vision-camera/lib/typescript/hooks/useFrameProcessor.d.ts:33:25
> 
> > npm ERR!     33 export declare function useFrameProcessor(frameProcessor: (frame: Frame) => void, dependencies: DependencyList): ReadonlyFrameProcessor;
> 
> > npm ERR!                                ~~~~~~~~~~~~~~~~~
> 
> > npm ERR!     'useFrameProcessor' is declared here.
> 
> > npm ERR! 
> 
> > npm ERR! 
> 
> > npm ERR! Found 2 errors in 2 files.
> 
> > npm ERR! 
> 
> > npm ERR! Errors  Files
> 
> > npm ERR!      1  src/index.tsx:7
> 
> > npm ERR!      1  src/types.ts:3
> 
> > npm ERR! ✖ Failed to build definition files.
> 
> > npm ERR! npm WARN using --force Recommended protections disabled.
> 
> > ```
> 
> 
> 
> This error means that useRunInJs does not exist in work modules, now it is useRunOnJs, you can pay me and I will speed up the creation of a new package and help fix further errors.
> 
> 

Give me email contact. We can make a deal 😎

**Comment by gev2002** [comment]
@beatlecz  This is my email address, you can contact me there gev.avet.02@gmail.com.

**Comment by gev2002** [comment]
The plugin is available now.You can use it https://github.com/gev2002/react-native-vision-camera-text-recognition
By Supporting @beatlecz. 🥳🥳🥳🎉🎉🎉

**Pull request closed without merging**
